### ISSUE TITLE
e_axis_formatter does not appear to work

### ISSUE THREAD

**Issue by nschwamm** [JohnCoene/echarts4r#100]
The e_axis_formatter does not appear to work such that taking the examples from the reference guide (https://echarts4r.john-coene.com/reference/axis.html) do not even work.

For example: 
```r
 # use formatter
cars %>%
  dplyr::mutate(
    speed = speed / 25
  ) %>%
  e_charts(speed) %>%
  e_scatter(dist) %>%
  e_y_axis(
    formatter = e_axis_formatter("currency")
  ) %>%
  e_x_axis(
    formatter = e_axis_formatter("percent", digits = 0)
  )
```

This just shows an empty output for me.

In fact, any example with e_axis_formatter applied to the y axis appear to fail. 

```r
# y-axis example
cars %>%
  e_charts(speed) %>%
  e_line(dist) %>%
  e_y_axis(dist,formatter = e_axis_formatter("decimal")) %>%
  e_x_axis(speed)
```

If I try using it with the x axis, all the data disappears. 

```r
# x-axis example
cars %>%
  e_charts(speed) %>%
  e_line(dist) %>%
  e_x_axis(speed,formatter = e_axis_formatter("decimal")) %>%
  e_y_axis(dist)
```

**Comment by JohnCoene** [comment]
Sorry for the late response, took a bit of break in the summer. It does indeed not work, it's been a while since I worked on the axis formatter helpers, a lot of them are contributions from @artemklevtsov (thanks again!).

My understanding is that the underlying JavaScript function would have to dramatically change in order to apply to both axis but I may be wrong. I'll look into it.

**Comment by nschwamm** [comment]
Appreciate the response. Just for reference, the examples hold even if you are doing one at time. 

For example, neither of these work:

```
# y-axis
cars %>%
  e_charts(speed) %>%
  e_line(dist) %>%
  e_y_axis(dist,formatter = e_axis_formatter("decimal"))
```


```
# x-axis
cars %>%
  e_charts(speed) %>%
  e_line(dist) %>%
  e_x_axis(speed,formatter = e_axis_formatter("decimal"))
```

Any work around to format an axis without using the e_axis_formatter function for now?

**Comment by JohnCoene** [comment]
I think I have narrowed down the issue; would you happen to be on Linux?

**Comment by nschwamm** [comment]
These errors were caused on a Windows computer, however, the ultimate deployment will be to a linux server.

**Comment by JohnCoene** [comment]
What's the output of `stringi::stri_locale_info()$Language` on your machine?

**Comment by nschwamm** [comment]
```stringi::stri_locale_info()$Language``` prints "en"

That code produces the same error as the earlier example, as well as if I include ```locale = "en"``` in the y_axis_formatter example as well

**Comment by JohnCoene** [comment]
Should be fixed.

```r
remotes::install_github("JohnCoene/echarts4r")
```

**Comment by nschwamm** [comment]
No luck here. Same error persists.

**Comment by shrektan** [comment]
I haven't tested it but in case you are using RStudio to view the chart, I suggest you view the chart in the browser. I remember when there's certain javascript included in the chart, some of them can't be displayed well in RStudio's viewer but it's ok to use in the browser.

**Comment by nschwamm** [comment]
@shrektan that worked! Interesting that the javascript crashes in different ways for the x/y axis. But yes, that works! 

@JohnCoene maybe we can add this to the reference guide?

**Comment by JohnCoene** [comment]
Ah! Thank you @shrektan! I was totally out of ideas. I indeed don’t use RStudio but it’s to the best of my knowledge a browser (the whole of RStudio) you can right click inspect anything. I’ve encountered such issues in the past for the {signals} package: it had not occurred to me that this could be the issue here too.

I’ll add a note in the documentation. Thanks again @shrektan for isolating the issue and thank you @nschwamm for the bug report.

**Comment by JohnCoene** [comment]
It's now mentioned in documentation + if using RStudio the function `e_axis_formatter` emits a warning. Thanks both!
