### ISSUE TITLE
e_bar label cutoff

### ISSUE THREAD

**Issue by nschwamm** [JohnCoene/echarts4r#132]
Hi,

Looking at the following example:

```
tibble(
  group= c("Group 1", "Group 2", "Group 3", "Really Really Long Group 4","Really Really Long Group 5","Group 6"),
  values = c(1,2,3,4,5,6)
) %>%
  e_chart(group) %>%
  e_bar(values)
```

When labels are very long (i.e. group 4/5) it forces a heuristic to show which labels to show - in this case it shows 1,3,5.

![image](https://user-images.githubusercontent.com/11548800/75909441-1f915400-5e1a-11ea-8a5d-f0681723059a.png)

First, it doesn't actually appear that any axis label is longer than the bar, so I'm not sure why in the case it is forced to only show one. Second, do you know what heuristic is being used to determine how to show axis labels? Finally, one option I've used with other packages is using str_wrap from stringr in order to wrap the axis labels. However, when you try to wrap the group name, e_charts sanitizes the HTML. For example adding a mutate line, mutate(group = str_wrap(group,15)) produces the output "Really Really\nLong Group 5" which should add line breaks in the group field, but it does not.

I think the solution to this (while still maintaining the current model) would be to allow HTML in the axis labels, or otherwise allow for text wrapping.

Thanks!

**Comment by JohnCoene** [comment]
Perhaps an issue with the version of echarts4r you are on, on the development it works fine.

```r
library(echarts4r)

tibble::tibble(
  group= c("Group 1", "Group 2", "Group 3", "Really Really Long Group 4","Really Really Long Group 5","Group 6"),
  values = c(1,2,3,4,5,6)
) %>%
  dplyr::mutate(
    group = stringr::str_wrap(group, 15)
  ) %>% 
  e_chart(group) %>%
  e_bar(values)
```
![image](https://user-images.githubusercontent.com/7833796/75910820-d3143b80-5e4e-11ea-8940-934bb4646423.png)

I'm unsure about the heuristic used, it's not detailed in the [documentation](https://echarts.apache.org/en/option.html#xAxis.axisLabel.interval). Echarts producing responsive charts there needs to be a mechanism so that the plot shows fine regardless of the screen size.

You can also override that with the `interval` parameter under `axisLabel`. It defines the interval between labels and defaults to said heuristic (`auto`), if you set it to `0` then every label is shown but be aware that this might lead to them overlapping on small screens (e.g.: mobile).

```r
tibble::tibble(
  group= c("Group 1", "Group 2", "Group 3", "Really Really Long Group 4","Really Really Long Group 5","Group 6"),
  values = c(1,2,3,4,5,6)
) %>%
  e_chart(group) %>%
  e_bar(values) %>% 
  e_x_axis(
    axisLabel = list(
      interval = 0L
    )
  )
```

![image](https://user-images.githubusercontent.com/7833796/75911058-3900c300-5e4f-11ea-88b2-32ea01022b98.png)
 
Let me know if this answers your question.

**Comment by nschwamm** [comment]
This is exactly what I need - appreciate the help!
Thanks so much!

**Comment by JohnCoene** [comment]
Great, feel free to open any other issue if you encounter problems.

**Comment by acircleda** [comment]
I've found that flipping the charts to horizontal bars cuts off the axis labels. There should be some adjustment to the chart or an automatic wrapper.

```
tibble::tibble(
  group= c("Group 1", "Group 2", "Group 3", "Really Really Long Group 4","Really Really Long Group 5","Group 6"),
  values = c(1,2,3,4,5,6)
) %>%
  e_chart(group) %>%
  e_bar(values) %>% 
  e_x_axis(
    axisLabel = list(
      interval = 0
    )
  ) %>%
  e_flip_coords()
```

![image](https://user-images.githubusercontent.com/51770624/135363952-f8dc845b-c8d4-491d-96af-ce13cb8339b3.png)

**Comment by jjesusfilho** [comment]
@acircleda, you can use `e_grid(left = "20%")`, or another percentage to pad left the grid.
