### ISSUE TITLE
Map appears to be stretched horizontally

### ISSUE THREAD

**Issue by domsle** [JohnCoene/echarts4r#170]
Hello,

I am plotting some maps, and doing so results in countries having a bit stretched proportions:
![image](https://user-images.githubusercontent.com/18559095/87150334-20e3f900-c2b2-11ea-96b8-f2e7ecabadd2.png)
The image above shows, on top maps created sing echarts4r, and on bottom maps created using highcharter. 

It was created with code below:
```
output$lonLatRevenueMap <- renderEcharts4r({ 
  lonLatRevenue() %>% 
    e_charts(longitude) %>%
    em_map("Slovakia") %>%
    e_geo("Slovakia")
})

output$lonLatRevenueMap2 <- renderEcharts4r({ 
  lonLatRevenue() %>% 
    e_charts(longitude) %>%
    em_map("Poland") %>%
    e_geo("Poland")
})

output$lonLatRevenueMap3 <- renderHighchart({
  
  hcmap('countries/sk/sk-all', showInLegend = FALSE) %>% 
    hc_mapNavigation(enabled = TRUE) 
  
})
output$lonLatRevenueMap4 <- renderHighchart({
  
  hcmap('countries/pl/pl-all', showInLegend = FALSE) %>% 
    hc_mapNavigation(enabled = TRUE) 
  
})
```
I think it is not important to provide code in UI part of shiny app, as these are just plain maps.

Is this behaviour expected, or can be changed with some arguments?

**Comment by JohnCoene** [comment]
They do indeed do not look alike. I'm afraid I'm not very well versed in geo-spatial so I might be missing something but I suspect this has to do with projections, which is implemented in highchart.js but not echarts. echarts4r will just import the GeoJSON and use those polygons as-is so to speak but there is an `aspectScale` argument in [the docs](https://echarts.apache.org/en/option.html#geo.aspectScale) which might help.

```r
library(echarts4r)

e_charts() %>%
  echarts4r.maps::em_map("Poland") %>%
  e_geo("Poland", aspectScale = .6)
```

![image](https://user-images.githubusercontent.com/7833796/87153229-6bb43f80-c2b7-11ea-9fb5-f2f696c748e7.png)

Note that `echarts4r.maps` is just a convenience package that holds GeoJSONs, in order to properly compare highcharts and echarts we should use the same: highcharter downloads map data from: [code.highcharts.com/mapdata/](https://code.highcharts.com/mapdata/).

Does not work out of the box because echarts applies the aspect scaling factor

```r
pl_url <- "https://code.highcharts.com/mapdata/countries/pl/pl-all.geo.json"
pl <- geojsonio::geojson_read(pl_url)

# no aspect scale
e_charts() %>%
  e_map_register("polanball", pl) %>%
  e_geo(map = "polanball")
```

![image](https://user-images.githubusercontent.com/7833796/87153380-aae29080-c2b7-11ea-8e53-d1f6aec6433a.png)

Correcting for the aspect factor we obtain the map below, _which looks identical to highcharter_ (to me).

```r
# correcting scale 
e_charts() %>%
  e_map_register("polanball", pl) %>%
  e_geo(map = "polanball", aspectScale = 1)
```

![image](https://user-images.githubusercontent.com/7833796/87153425-bafa7000-c2b7-11ea-9f55-322bd62e5595.png)

Let me know if that is not clear.

**Comment by JohnCoene** [comment]
Did this help at all?

**Comment by domsle** [comment]
Thank you for replying so quickly.
Yes, this solves my problem.
