### ISSUE TITLE
How can i control output size

### ISSUE THREAD

**Issue by jiangnight** [JohnCoene/echarts4r#20]
Hello! where can i set the output width and height,when i use rmarkdown or just output?

**Comment by JohnCoene** [comment]
Use the `width` and `height` (integer = pixels, can also pass percentages) arguments in `e_charts` or `e_chart`.

```r
library(echarts4r)

# pixels
mtcars %>% 
    e_charts(qsec, width = 250, height = 150) %>% 
    e_line(mpg)

# percentages
mtcars %>% 
    e_charts(qsec, width = "50%", height = "75%") %>% 
    e_line(mpg)
```

**Responsiveness**

However I would advise only changing the `height` to pixels and keeping the `width` either unchanged or as `%` otherwise your charts will **not** be responsive anymore.

```r
# responsive
mtcars %>% 
    e_charts(qsec, height = "200") %>% 
    e_line(mpg)

# also responsive
mtcars %>% 
    e_charts(qsec, height = "200", width = "75%") %>% 
    e_line(mpg)
```

If you're in RStudio you can plot in the viewer and then resize it to see what I mean.

**Comment by jiangnight** [comment]
thanks a lot for you help! i got it
