### ISSUE TITLE
e_tooltip_item_formatter

### ISSUE THREAD

**Issue by sebastianottmann** [JohnCoene/echarts4r#261]
I want to display the decimal and big numbers marks in the german format (big mark = point / decimal mark = comma) in a graphic with the function e_axis_formatter and e_tooltip_item_formatter.

For this I have created the following code:

```
testdata %>%
  e_charts(datum) %>%
  e_line(bayern_gesamt) %>%
  e_datazoom(type="slider") %>%
  e_toolbox_feature(feature="saveAsImage") %>%
  e_legend(show=FALSE) %>%
  e_tooltip(trigger="item", formatter = e_tooltip_item_formatter("decimal", locale = "de-DE")) %>% 
  e_y_axis(formatter = e_axis_formatter("decimal", locale = "de-DE"))
```

On the y-axis does it work. On the tooltip unfortunately not, as the screenshot shows. Here the actual value 344668 is not displayed, but 2.021. I suspect that this value comes from the variable "date", although the value from the variable "bayern_gesamt" should be displayed. If I just insert e_tooltip() the value is displayed correctly, but with a comm as big mark.

![grafik](https://user-images.githubusercontent.com/59435828/104022651-ddb30600-51c0-11eb-94f8-205e05b5a5a4.png)

Do I have an mistake in my code or is this a bug?

Thanks for the help and the great R package.

**Comment by JohnCoene** [comment]
You're not doing anything wrong but I'm not sure it qualifies as a bug either.

This is a convenience function to construct the underlying JavaScript function (tooltip formatter) and is bound not work in all cases. Though admittedly I'm not sure why it does not work in this case; it has to determine the correct index of the dataset to use in the tooltip and it gets it wrong here (`x` instead of `y`).

Does the code below works? It does not make use of the convenience function and instead builds the JS function manually.

```r
df <- data.frame(
  x = 1:100,
  y = runif(100, 10^5, 2 * 10^5)
)

js <- htmlwidgets::JS(
  "function(params, ticket, callback) {
    var fmt = new Intl.NumberFormat(
      'de', // locale 
      {
        style: 'decimal', 
        maximumFractionDigits: 2, // 2 decimals
        minimumFractionDigits: 2
      }
    );

    return params.value[0] + '<br>' +
            params.marker + ' ' +
            params.seriesName + ': ' + fmt.format(parseFloat(params.value[1]));
  }"
)

e_charts(df, x) %>% 
  e_scatter(y, symbol_size = 10) %>% 
  e_tooltip(
    trigger = "item",
    formatter = js
  )
```

Apologies for this, hope this fixes it. Let me know.
