### ISSUE TITLE
time zones

### ISSUE THREAD

**Issue by fmmattioni** [JohnCoene/echarts4r#294]
Hey guys,

I was producing some graphs that have some timezones that I am not used to work with, such as `Australia/Queensland`.

Here is my issue: I can't make it `e_mark_line()` to work with it. I am wondering if there is some timezone conversion happening in the background?

**reprex that works:**

```r
library(echarts4r)
library(dplyr)
library(lubridate)

df <- tibble(
  time = seq(from = as_datetime("2021-01-01 08:00:00", tz = "CET"), to = as_datetime("2021-01-01 09:10:00", tz = "CET"), by = "1 min"),
  y = rnorm(71, mean = 100)
)

x <- as_datetime("2021-01-01 09:03:00", tz = "CET")

df %>% 
  e_charts(time) %>% 
  e_line(y) %>% 
  e_mark_line(
    data = list(xAxis = x),
    title = "label"
  )
```

**reprex that doesn't work:**

```r
library(echarts4r)
library(dplyr)
library(lubridate)

df <- tibble(
  time = seq(from = as_datetime("2021-01-01 08:00:00", tz = "Australia/Queensland"), to = as_datetime("2021-01-01 09:10:00", tz = "Australia/Queensland"), by = "1 min"),
  y = rnorm(71, mean = 100)
)

x <- as_datetime("2021-01-01 09:03:00", tz = "Australia/Queensland")

df %>% 
  e_charts(time) %>% 
  e_line(y) %>% 
  e_mark_line(
    data = list(xAxis = x),
    title = "label"
  )
```

**Comment by fmmattioni** [comment]
UTC is also not working:

```r
library(echarts4r)
library(dplyr)
library(lubridate)

df <- tibble(
  time = seq(from = as_datetime("2021-01-01 08:00:00", tz = "UTC"), to = as_datetime("2021-01-01 09:10:00", tz = "UTC"), by = "1 min"),
  y = rnorm(71, mean = 100)
)

x <- as_datetime("2021-01-01 09:03:00", tz = "UTC")

df %>% 
  e_charts(time) %>% 
  e_line(y) %>% 
  e_mark_line(
    data = list(xAxis = x),
    title = "label"
  )
```

**Comment by fmmattioni** [comment]
Everything works if I transform `time` and `x` into `character()`, but I wonder if that is the way to go?

**Comment by JohnCoene** [comment]
Interesting, I think it's both on the side of echarts4r/htmlwidgets and ECharts.js.

When the `x` passed to `e_charts` is an object of type `POSIX` or `Date`, echarts4r, under the hood, does some mysterious handling to ensure ECharts.js treats that as a proper timestamp/date.

However, that does not happen for `e_mark_line`, it ends up as a string and treated as such by ECharts.js. Does the below solve the problem? 

```r
df <- tibble(
  time = seq(
    from = as_datetime("2021-01-01 08:00:00", tz = "Australia/Queensland"), 
    to = as_datetime("2021-01-01 09:10:00", tz = "Australia/Queensland"), 
    by = "1 min"
  ),
  y = rnorm(71, mean = 100)
)

x <- as_datetime("2021-01-01 09:03:00", tz = "Australia/Queensland")

# convert to character
x <- as.character(x)

df %>% 
  e_charts(time) %>% 
  e_line(y) %>% 
  e_mark_line(
    data = list(xAxis = x),
    title = "label"
  )
```

It's because including the timezone in the core dataset of the serie is properly treated by ECharts.js but not in the `mark*` function, it fails to parse the timestamp, converting to `character` remove the timezone and seems to solve the issue.

**Comment by JohnCoene** [comment]
I just saw your last comment, sorry. Yes, that seems to be the way.

**Comment by fmmattioni** [comment]
Perfect, thanks a lot for the explanation, John!
