### ISSUE TITLE
Freeing up memory in shiny

### ISSUE THREAD

**Issue by fmmattioni** [JohnCoene/echarts4r#303]
Hi guys,

I have a shiny app that uses `echarts4r` for all the plots. The app is divided into 4 different tabs, and in each tab there are a few `echarts` plots.

I was wondering if when switching to different tabs I could somehow "unrender" the previous plots? This would optimize the memory required in production. Right now, if I go over all 4 tabs and it renders all the plots, the app can consume quite a lot of memory.

Do you know if there is a way to achieve this?

Here is an example scenario to illustrate the problem:

- App starts on Tab 1, 3 plots are rendered (Currently required memory: 50 Mb).
- User clicks on Tab 2, 10 plots are rendered (Currently required memory: 200 Mb).
- User comes back to Tab 1, and the currently required memory is still 200 Mb.

This would require the plots to be rendered every time the user goes to a certain tab, but I guess that would be better than consuming memory that might not be needed anymore.

Any thoughts?

**Comment by swsoyee** [comment]
If I'm correct, switch the tab will not re-render the plot (my app for example : https://covid-2019.live/en).
But if your data which you send to `e_charts()` changed when switching tab, the plot will render again.

**Comment by fmmattioni** [comment]
Thanks, @swsoyee ! Cool app, btw!

I was looking for a way that, when switching tabs, the plots on the previous tab would "unrender", if that makes sense.

**Comment by swsoyee** [comment]
Sorry, `Currently required memory` means the memory used in user's machine? If you are trying to free up memory on the user's side I'm sorry I don't know the solution. 😭

**Comment by JohnCoene** [comment]
There is currently no proxy to do that but it can be achieved with a bit of JavaScript.

```r
library(shiny)
library(echarts4r)

ui <- fluidPage(
  tags$script(
    "Shiny.addCustomMessageHandler('clear-graph', function(msg){
      let widget = HTMLWidgets.find('#plot');
      let chart = widget.getChart();
      chart.dispose(); 
    })"
  ),
  actionButton("clear", "Clear"),
  actionButton("draw", "redraw"),
  echarts4rOutput("plot")
)

server <- function(input, output, session){
  output$plot <- renderEcharts4r({
    input$draw
    e_charts(cars, speed) %>% 
      e_scatter(dist)
  })

  observeEvent(input$clear, {
    session$sendCustomMessage('clear-graph', list())
  })
}

shinyApp(ui, server)
```

*Check that this actually reduces the data load in the browser, I'm not sure*

However, I'm not sure it's a good idea. To the best of my knowledge having 200Mb in the browser is not ideal but is still reasonable, the problem is often loading this data into the browser.

In shiny this goes through the websocket, loading 200Mb at once would not be a good idea but here it's done tab by tab.
Also, once this is done revisiting already visited tab does not re-render the chart as far as I know. 

In your paradigm charts that were previously rendered would have to be re-rendered. So overall the data loaded in the browser would be less but the transfer of data from the server to clients would increase; and I think this is worse.

**Comment by fmmattioni** [comment]
That makes a lot of sense, @JohnCoene ! Thanks a lot for all the detailed info!
