### ISSUE TITLE
How to use e_resize()?

### ISSUE THREAD

**Issue by Camil88** [JohnCoene/echarts4r#376]
Hi, I would like user to resize the chart and I found `e_resize()` function in documentation. It seems to work with proxy only. However I added `e_resize` to `echarts4rProxy` but nothing happens, can't resize the chart. Here is a reproducible example:

```r
library(shiny)
library(dplyr)
library(echarts4r)

moduleServer <- function(id, module) {
    callModule(module, id)
}

# UI 1 #
mod_btn_UI <- function(id) {
    
    ns <- NS(id)
    tagList(
        actionButton(ns("btn1"), "Button 1"),
        echarts4rOutput(ns("plot"))
    )
}

# Server 1 #
mod_btn_server <- function(id){
    moduleServer(id, function(input, output, session) {
        
      ns <- NS(id)
      
      output$plot <- echarts4r::renderEcharts4r({
        mtcars %>%
          e_charts(qsec) %>%
          e_line(mpg)
         
      })
      
      observeEvent(input$btn1, {
        echarts4rProxy(ns("plot"), data = mtcars, x = qsec) %>% 
          e_line(drat) %>% 
          e_execute() %>% 
          e_resize()  # it seems not working - can't resize the chart
      })
    })
}

# App #
ui <- fluidPage(
    mod_btn_UI("test-btn")
)

server <- function(input, output, session) {
    mod_btn_server("test-btn")
}

shinyApp(ui = ui, server = server)

```

**Comment by JohnCoene** [comment]
This function was added for a corner use case and should really not be needed.

It forces the chart to resize (automatically handled otherwise) to fit its parent container.
In your example the parent container does not change dimension and thus the chart does not resize.

Please feel free to reopen if you think there is a use here and that it is in fact not working.
