### ISSUE TITLE
R crashes for larger datsets

### ISSUE THREAD

**Issue by swati-soulpageit** [JohnCoene/echarts4r#68]
Hi,

I am using R version 3.5.2.  I used "airquality" inbuilt dataset for practicing all the graphs.
Now, I am trying to use my own data set which is a "517272 rows 20 columns"  data matrix, but my R crashes every time I use this dataset. I tried to subset it to a smaller dataset "708 rows 10columns" data matrix and all the graphs work fine.
Can you please guide me

**Comment by JohnCoene** [comment]
Does R throw an error before crashing? Does is crash when using echarts4r or when you load the dataset?

**Comment by swati-soulpageit** [comment]
It crashes when I use echart4r . This is my code. I have used the same code
for smaller dataset (708*10) and it produces a beautiful graph. But when I
use the same for a larger dataset (517272 * 20), it goes blank.

data_final %>%
  e_charts(ISD_Number) %>%
  e_line(avg_ghi) %>%
  e_area(avg_dry_bulb, y_index = 1) %>%
  e_title("Line and area charts")

I have to force shut R after the screen goes blank.

--
Regards,
Swati Dhavala,
Data Scientist,
SoulPage IT Solutions.

**Comment by JohnCoene** [comment]
I believe it's because echarts4r needs to work on a copy of the dataset, which doubles the load on the RAM.

You do something like below though it's not a brilliant solution, if it works at all (the dataset is dumped after the copy is made so there is still a point at which the data could be too large).

```r
dat <- cars

# function that removes your dataset from the global environment 
# to only keep the one stored internally by echarts4r
clean <- function(e){
  rm(dat)
  return(e)
}

# inspect
head(dat)

dat %>% 
  e_charts(speed) %>%
  clean() %>%
  e_scatter(dist)

# removed
# dat does not exist anymore
dat
```

Probably you could more easily filter the dataset to only keep the columns you want to plot, thereby reducing the amount of data that is stored in your live memory _as well as_ the copy.

```r
library(dplyr)

# select columns to plot 
# make sure to OVERRIDE the dataset otherwise there's no point in this operation
mtcars <- mtcars %>%
  select(wt, qsec)

mtcars %>% 
  e_charts(qsec) %>%
  e_scatter(wt)
```

**Comment by swati-soulpageit** [comment]
Hi John,

I have tried to use the solution that you suggested, but still the same
problem.

When I work with a really small dataset, there is no problem.

Thanks for your help

--
Regards,
Swati Dhavala,
Data Scientist,
SoulPage IT Solutions.

**Comment by helgasoft** [comment]
@swati-soulpageit, your dataset is indeed too large. My RStudio went blank also on loading the chart.
A couple of things to try.
First, reduce the number of columns. _"517272 rows 20 columns"_, but you are using only 3, so the other 17 need to go.
Then, you could get/provide a glimpse of the data, so you/we know what the beast is. Like so:
```r
v <- 517272
data_final <- data.frame(ISD_Number = 1:v,   #sample(1:100, v, replace=TRUE),
           avg_ghi = sample(1:100, v, replace=TRUE),
           avg_dry_bulb = sample(1:100, v, replace=TRUE))
data_final %>% dplyr::glimpse()
```
You may also look up the data in 3D. It may take a minute or two, but it will work:
```r
data_final %>% e_charts(ISD_Number) %>% e_scatter_3d(avg_ghi, avg_dry_bulb)
```
At best, reduce the number of rows. 2D plots get messy just after a thousand points, not to mention half a million...
Maybe categorize the data and show it by groups instead of all at once?
If none of this helps ... you'll need a [bigger boat](https://thumbs.gfycat.com/PerkyVictoriousFish-mobile.mp4).
