### ISSUE TITLE
Clicking on radar legend does not toggle the right series

### ISSUE THREAD

**Issue by antoine-sachet** [JohnCoene/echarts4r#74]
This is apparent on the [radar demo](https://echarts4r.john-coene.com/articles/chart_types.html#radar).

Code to reproduce:

```r
df <- data.frame(
    x = LETTERS[1:5],
    y = runif(5, 1, 5),
    z = runif(5, 3, 7)
)

df %>% 
    e_charts(x) %>% 
    e_radar(y, max = 7, name = "radar") %>%
    e_radar(z, max = 7, name = "chart") %>%
    e_tooltip(trigger = "item")
```

Clicking on the first element of the legend, "radar", removes both the "radar" and "chart" series. It should only remove the first series.

**Comment by etiennebacher** [comment]
I am having the same bug, do you know how to fix it @JohnCoene?

**Comment by etiennebacher** [comment]
This bug only appears for radar plots (to my knowledge). For example, there are no problems with line plots:
```
library(echarts4r)

df <- data.frame(
  x = LETTERS[1:5],
  y = runif(5, 1, 5),
  z = runif(5, 3, 7)
)

# legend doesn't work with radar
df %>% 
  e_charts(x) %>% 
  e_radar(y, max = 7, name = "radar") %>%
  e_radar(z, max = 7, name = "chart")

# legend works with lines
df %>%
  e_charts(x) %>%
  e_line(y) %>%
  e_line(z)
```
I checked the preview in [`echarts.js` documentation](https://echarts.apache.org/en/option.html#radar) and the legend works well so I guess this bug comes from the R package. I tried to compare the code of `e_radar_` to the code of `e_line_` but I didn't find anything unusual (though I'm far from being an expert in R, and even less in JS). Any idea where this comes from?

**Comment by JohnCoene** [comment]
Sorry, I had overlooked this issue, I pushed a fix to Github main branch just now.

**Comment by daljio56** [comment]
one option is try to indicate that the first legend control the whole radar chart, and then add radar for each element, with that at lease each element has its buttom to be hide and show. 

It's a trick to try to overcome the problem, it not solve the real issue.


df <- data.frame(
  x = LETTERS[1:5],
  y = runif(5, 1, 5),
  z = runif(5, 3, 7)
)

df$w <- NA

df %>% 
  e_charts(x) %>% 
  e_radar(w, max = 7, name = "radar") %>%
  e_radar(y, max = 7, name = "var1") %>%
  e_radar(z, max = 7, name = "var2") %>%
  e_tooltip(trigger = "item")
