### ISSUE TITLE
Add multiple e_title

### ISSUE THREAD

**Issue by hiffman** [JohnCoene/echarts4r#83]
Hi John,
     Thank you for creating such a wonderful package! I have a question that
how to add multiple e_title for a graph. Here is an example, I want to
add different title for two pie charts. Below is my code, but not work.

```{r}
pie_test = data.frame( key=c("a","b","c"), value=c(10,20,40))

e_charts(data = pie_test, x=key) %>% 
  e_pie(serie = value,
        radius ="30%", 
        center = c('20%', '40%')) %>% 
  e_pie(serie = value,
        radius ="30%", 
        center = c('65%', '40%')) %>% 
  e_title( list(list(text = "First title", x='30%',  y='20%'),
                list(text = "Second title", x='70%', y='20%'))) 

```

**Comment by JohnCoene** [comment]
Thought I had implemented that before but it was buggy. It's now fixed, though you will need to reinstall, a "lite" install is good enough.

```r
remotes::install_github("JohnCoene/echarts4r")
```

Then for the multiple titles you will have to add them as shown below, generally ECharts (the original JS library) works with `left` and `right` rather than `x` and `y`: there are more options you can pass to the title [here](https://ecomfe.github.io/echarts-doc/public/en/option.html#title.id).

```r
library(echarts4r)

pie_test = data.frame( key=c("a","b","c"), value=c(10,20,40))

e_charts(data = pie_test, x=key) %>% 
  e_pie(serie = value,
        radius ="30%", 
        center = c('20%', '40%')) %>% 
  e_pie(serie = value,
        radius ="30%", 
        center = c('65%', '40%')) %>% 
  e_title(text = "First title", left='30%',  top='20%') %>% 
  e_title(text = "Second title", left='70%', top='20%')
```
![image](https://user-images.githubusercontent.com/7833796/60252980-d5a4b580-98fd-11e9-8cbe-78cc7fcce89b.png)

_Please re-open if it still does not work_

**Comment by hiffman** [comment]
It's working.Thank you for your patiently answer.

**Comment by JohnCoene** [comment]
You're most welcome, thank you for reporting this issue!
